version: '3'
services:
    live:
        image: live
        container_name: live
        build:
            context: .
        ports:
            - "10000:5000"
        environment:
            - DB_NAME=docker-compose
            - DB_CONNECTION=127.0.0.1:3306
