version: '3'
services:
    live_1:
        container_name: live_1
        build:
            context: .
        ports:
            - "6000:80"
        environment:
            - DB_NAME=docker-compose
            - DB_CONNECTION=127.0.0.1:3306
            - SERVICE_PORT=6000
            - SERVICE_IP=x.y
        volumes:
            - /E/Docker/Data/web/logs:/app/logs
        restart: always
    live_2:
        container_name: live_2
        build:
            context: .
        ports:
            - "6001:80"
        environment:
            - DB_NAME=docker-compose
            - DB_CONNECTION=127.0.0.1:3306
            - SERVICE_PORT=6001
            - SERVICE_IP=x.y
        volumes:
            - /E/Docker/Data/web/logs:/app/logs
        restart: always
    mysql:
        image: mysql:5.7
        container_name: mysql
        ports:
            - "3306:3306"
        volumes:
            - /E/Docker/Data/mysql:/var/lib/mysql
        restart: always
        environment:
            - TZ=Asia/Shanghai
            - MYSQL_ROOT_PASSWORD=123456